import { Star, Shield, Zap, Award, Crown, Diamond, Gem } from "lucide-react"

export interface Tier {
  id: string
  name: string
  level: number
  icon: React.ElementType
  color: string // text color
  bg: string // icon bg
  border: string // card border
  glow: string // glow color for hero
  gradient: string // gradient for badge
  minDeposit: number
  minReferrals: number
  minReferralDeposits: number
  bonus: number
  perks: string[]
}

export const TIERS: Tier[] = [
  {
    id: "welcome",
    name: "Welcome",
    level: 1,
    icon: Star,
    color: "text-slate-400",
    bg: "bg-muted",
    border: "border-slate-400/20",
    glow: "oklch(0.60 0.05 240)",
    gradient: "from-slate-500 to-slate-400",
    minDeposit: 0,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 0,
    perks: [
      "access_copy_trading",
      "basic_market_data",
      "email_support",
      "up_to_3_traders",
    ],
  },
  {
    id: "silver",
    name: "Silver",
    level: 2,
    icon: Shield,
    color: "text-slate-300",
    bg: "bg-muted",
    border: "border-slate-300/20",
    glow: "oklch(0.75 0.02 240)",
    gradient: "from-slate-400 to-slate-200",
    minDeposit: 10_000,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 250,
    perks: [
      "all_welcome_perks",
      "priority_support",
      "up_to_5_traders",
      "welcome_bonus_250",
      "reduced_fee_8",
    ],
  },
  {
    id: "silver_pro",
    name: "Silver Pro",
    level: 3,
    icon: Zap,
    color: "text-cyan-400",
    bg: "bg-cyan-400/10",
    border: "border-cyan-400/20",
    glow: "oklch(0.75 0.16 200)",
    gradient: "from-cyan-500 to-slate-300",
    minDeposit: 25_000,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 1_000,
    perks: [
      "all_silver_perks",
      "dedicated_account_mgr",
      "up_to_10_traders",
      "welcome_bonus_1000",
      "reduced_fee_6",
      "advanced_analytics",
    ],
  },
  {
    id: "gold",
    name: "Gold",
    level: 4,
    icon: Award,
    color: "text-yellow-400",
    bg: "bg-yellow-400/10",
    border: "border-yellow-400/20",
    glow: "oklch(0.85 0.20 85)",
    gradient: "from-yellow-500 to-amber-300",
    minDeposit: 50_000,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 2_000,
    perks: [
      "all_silver_pro_perks",
      "vip_support_line",
      "unlimited_traders",
      "welcome_bonus_2000",
      "copy_fee_4",
      "exclusive_webinars",
      "portfolio_review",
    ],
  },
  {
    id: "gold_pro",
    name: "Gold Pro",
    level: 5,
    icon: Crown,
    color: "text-amber-400",
    bg: "bg-amber-400/10",
    border: "border-amber-400/20",
    glow: "oklch(0.80 0.18 65)",
    gradient: "from-amber-500 to-yellow-300",
    minDeposit: 100_000,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 3_000,
    perks: [
      "all_gold_perks",
      "priority_withdrawals",
      "zero_copy_fee",
      "welcome_bonus_3000",
      "monthly_reports",
      "exclusive_trader_access",
      "strategy_sessions_1on1",
    ],
  },
  {
    id: "diamond",
    name: "Diamond",
    level: 6,
    icon: Diamond,
    color: "text-blue-400",
    bg: "bg-primary/10",
    border: "border-blue-400/20",
    glow: "oklch(0.70 0.18 240)",
    gradient: "from-blue-500 to-cyan-300",
    minDeposit: 250_000,
    minReferrals: 5,
    minReferralDeposits: 500_000,
    bonus: 10_000,
    perks: [
      "all_gold_pro_perks",
      "dedicated_relationship_mgr",
      "profit_sharing",
      "welcome_bonus_10000",
      "custom_risk",
      "quarterly_bonus",
      "early_access",
    ],
  },
  {
    id: "ambassador",
    name: "Ambassador",
    level: 7,
    icon: Gem,
    color: "text-purple-400",
    bg: "bg-purple-400/10",
    border: "border-purple-400/20",
    glow: "oklch(0.65 0.20 300)",
    gradient: "from-purple-600 to-pink-400",
    minDeposit: 1_000_000,
    minReferrals: 12,
    minReferralDeposits: 2_550_000,
    bonus: 50_000,
    perks: [
      "all_diamond_perks",
      "cobranded_marketing",
      "rev_share",
      "welcome_bonus_50000",
      "private_trader_fund",
      "annual_vip_event",
      "white_glove",
      "custom_leverage",
    ],
  },
]
