import { Star, Shield, Zap, Award, Crown, Diamond, Gem } from "lucide-react"

export interface Tier {
  id: string
  name: string
  level: number
  icon: React.ElementType
  color: string // text color
  bg: string // icon bg
  border: string // card border
  glow: string // glow color for hero
  gradient: string // gradient for badge
  minDeposit: number
  minReferrals: number
  minReferralDeposits: number
  bonus: number
  perks: string[]
}

export const TIERS: Tier[] = [
  {
    id: "welcome",
    name: "Welcome",
    level: 1,
    icon: Star,
    color: "text-slate-400",
    bg: "bg-muted",
    border: "border-slate-400/20",
    glow: "oklch(0.60 0.05 240)",
    gradient: "from-slate-500 to-slate-400",
    minDeposit: 0,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 0,
    perks: [
      "Access to copy trading",
      "Basic market data",
      "Email support",
      "Up to 3 traders to copy",
    ],
  },
  {
    id: "silver",
    name: "Silver",
    level: 2,
    icon: Shield,
    color: "text-slate-300",
    bg: "bg-muted",
    border: "border-slate-300/20",
    glow: "oklch(0.75 0.02 240)",
    gradient: "from-slate-400 to-slate-200",
    minDeposit: 10_000,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 250,
    perks: [
      "All Welcome perks",
      "Priority support",
      "Up to 5 traders to copy",
      "$250 welcome bonus",
      "Reduced copy fee 8%",
    ],
  },
  {
    id: "silver_pro",
    name: "Silver Pro",
    level: 3,
    icon: Zap,
    color: "text-cyan-400",
    bg: "bg-cyan-400/10",
    border: "border-cyan-400/20",
    glow: "oklch(0.75 0.16 200)",
    gradient: "from-cyan-500 to-slate-300",
    minDeposit: 25_000,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 1_000,
    perks: [
      "All Silver perks",
      "Dedicated account manager",
      "Up to 10 traders to copy",
      "$1,000 welcome bonus",
      "Reduced copy fee 6%",
      "Advanced market analytics",
    ],
  },
  {
    id: "gold",
    name: "Gold",
    level: 4,
    icon: Award,
    color: "text-yellow-400",
    bg: "bg-yellow-400/10",
    border: "border-yellow-400/20",
    glow: "oklch(0.85 0.20 85)",
    gradient: "from-yellow-500 to-amber-300",
    minDeposit: 50_000,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 2_000,
    perks: [
      "All Silver Pro perks",
      "VIP support line",
      "Unlimited traders to copy",
      "$2,000 welcome bonus",
      "Copy fee 4%",
      "Exclusive webinars & signals",
      "Personalised portfolio review",
    ],
  },
  {
    id: "gold_pro",
    name: "Gold Pro",
    level: 5,
    icon: Crown,
    color: "text-amber-400",
    bg: "bg-amber-400/10",
    border: "border-amber-400/20",
    glow: "oklch(0.80 0.18 65)",
    gradient: "from-amber-500 to-yellow-300",
    minDeposit: 100_000,
    minReferrals: 0,
    minReferralDeposits: 0,
    bonus: 3_000,
    perks: [
      "All Gold perks",
      "Priority withdrawals",
      "Zero copy fee",
      "$3,000 welcome bonus",
      "Monthly performance reports",
      "Exclusive trader access",
      "1-on-1 strategy sessions",
    ],
  },
  {
    id: "diamond",
    name: "Diamond",
    level: 6,
    icon: Diamond,
    color: "text-blue-400",
    bg: "bg-primary/10",
    border: "border-blue-400/20",
    glow: "oklch(0.70 0.18 240)",
    gradient: "from-blue-500 to-cyan-300",
    minDeposit: 250_000,
    minReferrals: 5,
    minReferralDeposits: 500_000,
    bonus: 10_000,
    perks: [
      "All Gold Pro perks",
      "Dedicated relationship manager",
      "Profit sharing programme",
      "$10,000 welcome bonus",
      "Custom risk strategies",
      "Quarterly bonus rewards",
      "Early access to new features",
    ],
  },
  {
    id: "ambassador",
    name: "Ambassador",
    level: 7,
    icon: Gem,
    color: "text-purple-400",
    bg: "bg-purple-400/10",
    border: "border-purple-400/20",
    glow: "oklch(0.65 0.20 300)",
    gradient: "from-purple-600 to-pink-400",
    minDeposit: 1_000_000,
    minReferrals: 12,
    minReferralDeposits: 2_550_000,
    bonus: 50_000,
    perks: [
      "All Diamond perks",
      "Co-branded marketing materials",
      "Revenue share on referrals",
      "$50,000 welcome bonus",
      "Access to private trader fund",
      "Annual VIP event invite",
      "White-glove concierge service",
      "Custom leverage arrangements",
    ],
  },
]
